<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.4" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="10.105.8" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.4" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="10.105.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jt808TerminalEmulator.Data\Jt808TerminalEmulator.Data.csproj" />
  </ItemGroup>

</Project>
